kind: Deployment
apiVersion: apps/v1
metadata:
  name: pricing-service
  labels:
    app: pricing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
      - name: pricing-service
        image: ascmn/pricing-service:173
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: ZIPKIN_HOST
          value: "zipkin"
        - name: ZIPKIN_PORT
          value: "9411"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5