kind: Service
apiVersion: v1
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
  - name: http
    protocol: TCP
    port: 9411
    targetPort: 9411