apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zipkin-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: zipkin.mn.lab.software.altkom.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: zipkin
          servicePort: 9411
