kind: Service
apiVersion: v1
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80