bases:
- agent-portal-gateway
- auth-service
- chat-service
- dashboard-service
- document-service
- payment-service
- policy-search-service
- policy-service
- pricing-service
- product-service
- web-vue
